# Generated by Django 5.1.6 on 2025-06-05 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticketanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketanswer',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='ticket.ticket'),
        ),
    ]
