# Generated by Django 5.1 on 2024-11-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('-created_date',)},
        ),
    ]
