# Generated by Django 5.1 on 2024-10-30 14:29

import gse.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=10, unique=True, validators=[gse.users.validators.validate_postal_code]),
        ),
    ]
