# Generated by Django 5.1 on 2024-11-05 05:10

import gse.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=10, validators=[gse.users.validators.validate_postal_code]),
        ),
    ]
