# Generated by Django 5.1.6 on 2025-06-05 14:06

import gse.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('-owner_profile',)},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[gse.users.validators.validate_iranian_phone_number], verbose_name='phone number'),
        ),
    ]
