# Generated by Django 5.1 on 2024-12-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('pending', 'درحال پردازش'), ('answered', 'پاسخ داده شده')], db_index=True, default='pending', max_length=10),
        ),
    ]
