# Generated by Django 5.1.6 on 2025-06-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-created_date',)},
        ),
    ]
