# Generated by Django 5.1 on 2024-11-16 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
