# Generated by Django 5.1 on 2024-11-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
