# Generated by Django 5.1 on 2024-11-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_slug_alter_productcategory_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='update_date',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='productmedia',
            old_name='update_date',
            new_name='updated_date',
        ),
    ]
