# Generated by Django 5.1 on 2024-12-09 15:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productreview_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='products', to='products.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='final_price',
            field=models.DecimalField(db_index=True, decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(db_index=True, decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_sub',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'عکس'), ('video', 'ویدیو')], db_index=True, max_length=10, verbose_name='نوع رسانه'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rate',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
