# Generated by Django 5.1 on 2025-01-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_available_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
