# Generated by Django 5.1.6 on 2025-06-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_media_url_productmedia_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('-created_date',), 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='productdetail',
            options={'ordering': ('-product',)},
        ),
        migrations.AlterModelOptions(
            name='productmedia',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ('-created_date',)},
        ),
    ]
