# Generated by Django 5.1 on 2024-11-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_usable',
            field=models.BooleanField(default=False),
        ),
    ]
