# Generated by Django 5.1 on 2024-11-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_coupon_is_usable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
    ]
