# Generated by Django 5.1 on 2024-11-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderitem_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='updated_data',
            new_name='updated_date',
        ),
    ]
