# Generated by Django 5.1 on 2024-11-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_updated_data_orderitem_updated_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-updated_date',)},
        ),
    ]
