# Generated by Django 5.1 on 2024-11-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_usable',
        ),
    ]
