# Generated by Django 5.1 on 2024-12-09 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_order_coupon_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_usage_limit',
            field=models.PositiveIntegerField(db_index=True, default=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('success', 'پرداخت شده'), ('pending', 'درحال پردازش'), ('cancelled', 'لغو شده')], db_index=True, default='pending', max_length=10, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
