# Generated by Django 5.1.6 on 2025-06-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_coupon_code_alter_coupon_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('-created_date',)},
        ),
    ]
